title: The Monterey Mural by Guillermo Wagner Granizo
description: A tribute to the colorful tile mural history of Monterey, California, created by Guillermo Wagner Granizo in 1984. The mural is outdoors on the west wall of the Monterey Conference Center and features dozens of scenes across centuries of equally colorful history in (Alta) California’s first capital.
google_analytics: 
show_downloads: false
theme: 

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
